#!/usr/bin/python

import subprocess
import os
import sys
import json

class Node:
  pass

def parseStream(string):
  parsedStream = Node()
  for field in string.split("|"):
    fieldPair = field.split("=")
    if len(fieldPair) == 2:
      [key, value] = fieldPair
      keyPair = key.split(":")
      if len(keyPair) == 2:
        [superKey, subKey] = keyPair
        if hasattr(parsedStream, superKey):
          node = getattr(parsedStream, superKey)
        else:
          node = Node()
          setattr(parsedStream, superKey, node)
        setattr(node, subKey, value)
      else:
        setattr(parsedStream, key, value)
  return parsedStream

filename = sys.argv[1]

try:
  with open("database", "r") as databaseFile:
    database = json.loads(databaseFile.read())
except:
  database = []

record = None
for data in database:
  pass

if not record:
  record = {"name": filename}

database.append(record)

with open("database", "w") as databaseFile:
  databaseFile.write(json.dumps(database, indent = 2))

streams = []
ffprobe = subprocess.Popen(
  ["ffprobe", "-show_streams", "-print_format", "compact", filename],
  stdout = subprocess.PIPE,
  stderr = open(os.devnull, 'w'))
for line in ffprobe.stdout:
  streams.append(parseStream(line.strip()))
